#default_sched = "scx_lavd" # Edit this line to the scheduler you want scx_loader to start at boot
#default_mode = "LowLatency" # Possible values: "Auto", "Gaming", "LowLatency", "PowerSave".

default_sched = "scx_bpfland"
default_mode = "LowLatency"
#default_mode = "Server"

# To apply:
# $ systemctl restart scx_loader.service

[scheds.scx_bpfland]
auto_mode = []
gaming_mode = ["-s", "10000", "-S", "1000", "-l", "10000", "-p", "-k"]
lowlatency_mode = ["-s", "1600", "-S", "80", "-l", "11000"]
powersave_mode = ["-s", "30000", "-S", "3000", "-l", "40000"]
server_mode = ["-s", "60000", "-S", "20000", "-l", "6000", "-p", "-k", "-n"]

[scheds.scx_rusty]
auto_mode = []
gaming_mode = ["-u", "10000", "-o", "1000", "-g", "1", "-D", "90.0", "-K", "100.0"]
lowlatency_mode = ["-u", "8000", "-o", "250", "-g", "1", "-D", "94.0", "-K", "970.0", "-I", "0.06"]
powersave_mode = ["-u", "20000", "-o", "2000", "-g", "0", "-D", "50.0", "-K", "50.0"]
server_mode = ["-f", "-u", "20000", "-o", "2000", "-g", "1", "-D", "90.0", "-K", "100.0"]

[scheds.scx_lavd]
auto_mode = ["--autopilot"]
gaming_mode = ["--performance", "--slice-max-us", "5000", "--slice-min-us", "300"]
lowlatency_mode = ["--performance", "--slice-max-us", "1100", "--slice-min-us", "60"]
powersave_mode = ["--powersave", "--slice-max-us", "10000", "--slice-min-us", "500"]
server_mode = ["--performance", "--slice-max-us", "80000", "--slice-min-us", "20000"]

[scheds.scx_flash]
auto_mode = []
gaming_mode = ["-s", "10000", "-l", "12500", "-u"]
lowlatency_mode = ["-s", "5000", "-l", "26700", "-u"]  # Увеличено значение -l
powersave_mode = ["-s", "20000", "-l", "10000"]
server_mode = ["-s", "20000", "-l", "-12500", "-k", "-u"]
